name: Release

on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'publish?'
        default: true
        type: boolean

jobs:
  testing:
    name: Matrix Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pnpm-version: [9.12, 9.13, 9.14, 9.15, 10.12, 10.13]

    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm, node
        uses: ./.github/actions/setup-pnpm-node
        with:
          pnpm-version: ${{ matrix.pnpm-version }}

      - name: Testing
        run: |
          pnpm install
          DEBUG=1 pnpm test

  release:
    name: Publish to npmjs (latest pnpm)
    runs-on: ubuntu-latest
    needs: testing
    if: github.event.inputs.publish == 'true'

    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm, node

        uses: ./.github/actions/setup-pnpm-node
        with:
          pnpm-version: latest

      - name: Publish
        run: |
          cat > "$HOME/.npmrc" << EOF
          //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          EOF
          pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
